### ISSUE TITLE
linux test

### ISSUE THREAD

**Issue by MuGdxy** [MuGdxy/muda#17]
[linux branch](https://github.com/MuGdxy/muda/tree/linux)
**MSVC**: 
- muda_test & muda_example & muda_pg
  - ✔️  compile & link & run

**GCC7.5**:
- muda_test
  - ✔️ compile & link
  - ❓  run (NO TEST YET)
- muda_example
  - ✔️ compile & link
  - ❓  run (NO TEST YET)
- muda_pg 
  - ❓ gui support(TODO)

**Comment by MuGdxy** [comment]
to test:
``` bash
xmake f --example=true --test=true
```
modify [xmake.lua](https://github.com/MuGdxy/muda/blob/linux/xmake.lua) to fix linux GUI problem:
- [GUI TODO1](https://github.com/MuGdxy/muda/blob/1b14da97f70a25d5c6baf2dbef54e094d1d1e498/xmake.lua#L65)
- [GUI TODO2](https://github.com/MuGdxy/muda/blob/1b14da97f70a25d5c6baf2dbef54e094d1d1e498/xmake.lua#L86)

**Comment by MuGdxy** [comment]
CUDA 11.1:
Problem:
- thrust universal unsupported

**Comment by MuGdxy** [comment]
see [version.h](https://github.com/MuGdxy/muda/blob/linux/src/core/muda/tools/version.h).

we take the cuda 11.6 as the baseline.
if the cuda version is higher than 11.6, all macros below will be defined, and the corresponding code will be active.
- MUDA_BASELINE_CUDACC_VER_SATISFIED
- MUDA_WITH_THRUST_UNIVERSAL
- MUDA_WITH_GRAPH_MEMORY_ALLOC_FREE

[commit](https://github.com/MuGdxy/muda/commit/d28ec9c759b06575a63a7223239ac593d1b083f1)

**Comment by sailing-innocent** [comment]
Ubuntu2004+CUDA12.0+GCC9
muda_test
✔️ compile & link
✔️ run ( with condition of numerical fault )
muda_example
✔️ compile & link
✔️ run ( without condition)
muda_pg
❓ gui support(TODO)
