### ISSUE TITLE
Problem: out-of-bound check not working

### ISSUE THREAD

**Issue by Da1sypetals** [MuGdxy/muda#53]
This code taken from the Zhihu tutorial should trigger out-of-bound check but did not.

gcc/g++ 11.4.0
cuda 11.5

```cpp
#include <Eigen/Eigen>
#include <iostream>
#include <muda/muda.h>

#define MUDA_CHECK_ON 1

namespace md = muda;

int main() {

    constexpr int N = 1024;
    md::HostVector<float> hA(N), hB(N), hC(N);
    md::DeviceVector<float> dA(N), dB(N), dC(N / 2);

    // initialize A and B using random numbers
    auto rand = [] { return std::rand() / (float)RAND_MAX; };
    std::generate(hA.begin(), hA.end(), rand);
    std::generate(hB.begin(), hB.end(), rand);

    // copy A and B to device
    dA = hA;
    dB = hB;

    // block size = 256
    md::ParallelFor(256)
        .apply(
            N,
            [dC = dC.viewer(),        // | this is a capture list              |
             dA = dA.cviewer(),       // | map from device_vector to a viewer  |
             dB = dB.cviewer()]       // | which is the most muda-style part!  |
            __device__(int i) mutable // place "mutable" to make dC modifiable
            {
                dC(i + 1) = dA(i) + dB(i);
                md::print("%f\n", dC(i));
            })
        .wait(); // wait the kernel to finish

    // copy C back to host
    hC = dC;
}

```

I wonder if my code has mistake or if something went wrong.
Thanks a lot in advance.

**Comment by MuGdxy** [comment]
If you compile the code in Release mode, there is no runtime check in muda.
So try to use the RelWithDebugInfo mode or just Debug mode.

**Comment by MuGdxy** [comment]
It's not a good idea to define MUDA_CHECK_ON manually in the source code, just define it in the Preprocessor.
If you have to define it manually in the source code, you should define `#define MUDA_CHECK_ON 1` before including any muda headers.

**Comment by Da1sypetals** [comment]
How do i make sure I compile under Debug mode? 
I deleted the `build` directory, made a new one and used this command
```
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
./main
```
and the problem persists.

**Comment by MuGdxy** [comment]
`std::cout << muda::RUNTIME_CHECK_ON << std::endl` to see if the runtime check is truly enabled.

**Comment by Da1sypetals** [comment]
It turns out that it was 0.

`muda/muda_config.h` has this code:
```
#ifndef MUDA_CHECK_ON
#define MUDA_CHECK_ON 0
#endif
```

Do I have to modify this code to make it work? Or is there a _proper_ way to do this?

**Comment by MuGdxy** [comment]
You may try this, `cmake . -DMUDA_FORCE_CHECK=ON`.

**Comment by Da1sypetals** [comment]
No it does not work :sob:

**Comment by MuGdxy** [comment]
Then, can you open a repository to contain your code, and I will try to fix that later?

**Comment by Da1sypetals** [comment]
The complete setting is:

main.cu
```cpp
#include <Eigen/Eigen>
#include <iostream>
#include <muda/muda.h>

namespace md = muda;

int main() {

    std::cout << muda::RUNTIME_CHECK_ON << std::endl;

    constexpr int N = 1024;
    md::HostVector<float> hA(N), hB(N), hC(N);
    md::DeviceVector<float> dA(N), dB(N), dC(N / 2);

    // initialize A and B using random numbers
    auto rand = [] { return std::rand() / (float)RAND_MAX; };
    std::generate(hA.begin(), hA.end(), rand);
    std::generate(hB.begin(), hB.end(), rand);

    // copy A and B to device
    dA = hA;
    dB = hB;

    // block size = 256
    md::ParallelFor(256)
        .apply(
            N,
            [dC = dC.viewer(),        // | this is a capture list              |
             dA = dA.cviewer(),       // | map from device_vector to a viewer  |
             dB = dB.cviewer()]       // | which is the most muda-style part!  |
            __device__(int i) mutable // place "mutable" to make dC modifiable
            {
                dC(i + 1) = dA(i) + dB(i);
                md::print("%f\n", dC(i));
            })
        .wait(); // wait the kernel to finish

    // copy C back to host
    hC = dC;
}

```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15...3.26)

set(CMAKE_C_COMPILER "/usr/bin/gcc")
set(CMAKE_CXX_COMPILER "/usr/bin/g++")

project(template LANGUAGES CXX CUDA)
set(CMAKE_CXX_STANDARD 17)

set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --expt-relaxed-constexpr --extended-lambda")

set(EIGEN_INCLUDE_DIR "extern/eigen")
set(MUDA_INCLUDE_DIR "extern/muda/src")

add_executable(main main.cu)

target_include_directories(main PUBLIC ${MUDA_INCLUDE_DIR})
target_include_directories(main PUBLIC ${EIGEN_INCLUDE_DIR})

set_target_properties(main PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
```

Eigen and Muda are cloned under `extern/eigen` and `extern/muda` directories.
I did not add them as submodule so opening a repo may not describe my file structure(?)
Simply follow the steps should reproduce the results.
> I also wonder what a proper startup template, with a CMakeLists.txt and a main.cu, should be like (because simply copying headers results in many compilation errors). Grateful if one could be provided.

**Comment by MuGdxy** [comment]
I provide a starting point for you, https://github.com/MuGdxy/muda-app/tree/cmake-mini. Build the project following the readme and then plug your code in it. I tested it on Linux, which works well.

It's not recommended to use an old-style CMake like the above.

**Comment by Da1sypetals** [comment]
The example works well, thanks.

**Comment by MuGdxy** [comment]
Ok, if nothing goes wrong, please close the issue 😄
